name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  MarkdownLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Check Markdown files
      uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        globs: '**/*.mdc'
